/* AQIBS WEB2 — JKBOSE study catalogue
   Notes = official NCERT chapter PDFs (full chapter lists)
   Books = official NCERT textbook readers
   Papers = official JKBOSE model test papers
*/
const NCERT = "https://ncert.nic.in/textbook/pdf/";
const NCERT_READ = "https://ncert.nic.in/textbook.php?";
const JKBOSE_PDF = "https://web.archive.org/web/20250201163152/https://jkbose.nic.in/pdf/";
const JKBOSE_QB = "https://web.archive.org/web/20250424182817/https://jkbose.nic.in/pdf/";

function ncert(code) {
  const pdf = `${NCERT}${code}.pdf`;
  return { viewUrl: pdf, downloadUrl: pdf };
}

function jkbosePaper(file, fromQuestionBank = false) {
  const pdf = `${fromQuestionBank ? JKBOSE_QB : JKBOSE_PDF}${encodeURI(file)}`;
  return { viewUrl: pdf, downloadUrl: pdf };
}

function ncertBook(query, firstChapter) {
  return {
    viewUrl: `${NCERT_READ}${query}`,
    downloadUrl: `${NCERT}${firstChapter}.pdf`,
  };
}

function chapters(classId, subject, prefix, titles) {
  return titles.map((title, i) => {
    const n = String(i + 1).padStart(2, "0");
    return {
      id: `${classId}-${subject}-${i + 1}`,
      subject,
      chapter: String(i + 1),
      title,
      ...ncert(`${prefix}${n}`),
    };
  });
}

const STUDY_DATA = {
  "10": {
    label: "Class 10th",
    streams: null,
    subjects: [
      { id: "eng", name: "English" },
      { id: "math", name: "Mathematics" },
      { id: "sci", name: "Science" },
      { id: "sst", name: "Social Science" },
      { id: "hin", name: "Hindi" },
    ],
    notes: [
      ...chapters("10", "eng", "jeff1", [
        "A Letter to God",
        "Nelson Mandela: Long Walk to Freedom",
        "Two Stories about Flying",
        "From the Diary of Anne Frank",
        "Glimpses of India",
        "Mijbil the Otter",
        "Madam Rides the Bus",
        "The Sermon at Benares",
        "The Proposal",
        "Dust of Snow / Fire and Ice",
        "A Tiger in the Zoo / How to Tell Wild Animals",
      ]),
      ...chapters("10", "math", "jemh1", [
        "Real Numbers",
        "Polynomials",
        "Pair of Linear Equations in Two Variables",
        "Quadratic Equations",
        "Arithmetic Progressions",
        "Triangles",
        "Coordinate Geometry",
        "Introduction to Trigonometry",
        "Some Applications of Trigonometry",
        "Circles",
        "Areas Related to Circles",
        "Surface Areas and Volumes",
        "Statistics",
        "Probability",
      ]),
      ...chapters("10", "sci", "jesc1", [
        "Chemical Reactions and Equations",
        "Acids, Bases and Salts",
        "Metals and Non-metals",
        "Carbon and its Compounds",
        "Life Processes",
        "Control and Coordination",
        "How do Organisms Reproduce?",
        "Heredity",
        "Light — Reflection and Refraction",
        "The Human Eye and the Colourful World",
        "Electricity",
        "Magnetic Effects of Electric Current",
        "Our Environment",
      ]),
      { id: "10-sst-1", subject: "sst", chapter: "1", title: "The Rise of Nationalism in Europe", ...ncert("jess101") },
      { id: "10-sst-2", subject: "sst", chapter: "2", title: "Nationalism in India", ...ncert("jess102") },
      { id: "10-sst-3", subject: "sst", chapter: "3", title: "The Making of a Global World", ...ncert("jess103") },
      { id: "10-sst-4", subject: "sst", chapter: "4", title: "The Age of Industrialisation", ...ncert("jess104") },
      { id: "10-sst-5", subject: "sst", chapter: "5", title: "Print Culture and the Modern World", ...ncert("jess105") },
      { id: "10-sst-6", subject: "sst", chapter: "6", title: "Resources and Development", ...ncert("jess201") },
      { id: "10-sst-7", subject: "sst", chapter: "7", title: "Forest and Wildlife Resources", ...ncert("jess202") },
      { id: "10-sst-8", subject: "sst", chapter: "8", title: "Water Resources", ...ncert("jess203") },
      { id: "10-sst-9", subject: "sst", chapter: "9", title: "Agriculture", ...ncert("jess204") },
      { id: "10-sst-10", subject: "sst", chapter: "10", title: "Minerals and Energy Resources", ...ncert("jess205") },
      { id: "10-sst-11", subject: "sst", chapter: "11", title: "Manufacturing Industries", ...ncert("jess206") },
      { id: "10-sst-12", subject: "sst", chapter: "12", title: "Lifelines of National Economy", ...ncert("jess207") },
      { id: "10-sst-13", subject: "sst", chapter: "13", title: "Power Sharing", ...ncert("jess301") },
      { id: "10-sst-14", subject: "sst", chapter: "14", title: "Federalism", ...ncert("jess302") },
      { id: "10-sst-15", subject: "sst", chapter: "15", title: "Gender, Religion and Caste", ...ncert("jess303") },
      { id: "10-sst-16", subject: "sst", chapter: "16", title: "Political Parties", ...ncert("jess304") },
      { id: "10-sst-17", subject: "sst", chapter: "17", title: "Outcomes of Democracy", ...ncert("jess305") },
      { id: "10-sst-18", subject: "sst", chapter: "18", title: "Development", ...ncert("jess401") },
      { id: "10-sst-19", subject: "sst", chapter: "19", title: "Sectors of the Indian Economy", ...ncert("jess402") },
      { id: "10-sst-20", subject: "sst", chapter: "20", title: "Money and Credit", ...ncert("jess403") },
      { id: "10-sst-21", subject: "sst", chapter: "21", title: "Globalisation and the Indian Economy", ...ncert("jess404") },
      { id: "10-sst-22", subject: "sst", chapter: "22", title: "Consumer Rights", ...ncert("jess405") },
      ...chapters("10", "hin", "jhks1", [
        "सूरदास",
        "तुलसीदास",
        "देव",
        "जयशंकर प्रसाद",
        "सूर्यकांत त्रिपाठी 'निराला'",
        "नागार्जुन",
        "गिरिजा कुमार माथुर",
        "ऋतुराज",
        "मंगलेश डबराल",
        "स्वयं प्रकाश",
        "रामवृक्ष बेनीपुरी",
        "यशपाल",
        "सर्वेश्वर दयाल सक्सेना",
        "मन्नू भंडारी",
        "महावीर प्रसाद द्विवेदी",
        "यतीन्द्र मिश्र",
        "भदंत आनंद कौसल्यायन",
      ]),
    ],
    papers: [
      { id: "10-eng-mtp", subject: "eng", title: "English Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTPGenEnglish10th.pdf") },
      { id: "10-eng-qb", subject: "eng", title: "English Question Bank", year: "JKBOSE", kind: "Question bank", ...jkbosePaper("Question_Bank_of_English_for_Class_10th.pdf", true) },
      { id: "10-math-mtp", subject: "math", title: "Mathematics Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Mathematics 10th.pdf") },
      { id: "10-sci-mtp", subject: "sci", title: "Science Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Science 10th.pdf") },
      { id: "10-sci-chem", subject: "sci", title: "Chemistry — Chemical Reactions and Equations", year: "JKBOSE", kind: "Question bank", ...jkbosePaper("Chemistry_Class_10th_Chemical_Reactions_and_Equations.pdf", true) },
      { id: "10-sst-mtp", subject: "sst", title: "Social Science Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP S. Science 10th.pdf") },
      { id: "10-sst-qb", subject: "sst", title: "Social Science Question Bank", year: "JKBOSE", kind: "Question bank", ...jkbosePaper("Question_Bank_of_Social_Science_for_Class_10th.pdf", true) },
      { id: "10-hin-mtp", subject: "hin", title: "Hindi Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("10-Hindi-Main.pdf") },
      { id: "10-hin-qb", subject: "hin", title: "Hindi Question Bank", year: "JKBOSE", kind: "Question bank", ...jkbosePaper("Question_Bank_of_Hindi_for_Class_10th.pdf", true) },
    ],
    books: [
      { id: "10-eng-tb", subject: "eng", title: "First Flight", kind: "Textbook", ...ncertBook("jeff1=0-11", "jeff101") },
      { id: "10-eng-sup", subject: "eng", title: "Footprints without Feet", kind: "Supplementary", ...ncertBook("jefp1=0-10", "jefp101") },
      { id: "10-math-tb", subject: "math", title: "Mathematics Class 10", kind: "Textbook", ...ncertBook("jemh1=0-14", "jemh101") },
      { id: "10-sci-tb", subject: "sci", title: "Science Class 10", kind: "Textbook", ...ncertBook("jesc1=0-13", "jesc101") },
      { id: "10-sst-h", subject: "sst", title: "India and the Contemporary World II", kind: "History", ...ncertBook("jess1=0-5", "jess101") },
      { id: "10-sst-g", subject: "sst", title: "Contemporary India II", kind: "Geography", ...ncertBook("jess2=0-7", "jess201") },
      { id: "10-sst-p", subject: "sst", title: "Democratic Politics II", kind: "Political Science", ...ncertBook("jess3=0-5", "jess301") },
      { id: "10-sst-e", subject: "sst", title: "Understanding Economic Development", kind: "Economics", ...ncertBook("jess4=0-5", "jess401") },
      { id: "10-hin-tb", subject: "hin", title: "क्षितिज भाग 2", kind: "Textbook", ...ncertBook("jhks1=0-17", "jhks101") },
    ],
  },

  "11": {
    label: "Class 11th",
    streams: [
      { id: "med", name: "Medical" },
      { id: "nmed", name: "Non-Medical" },
      { id: "arts", name: "Arts" },
      { id: "com", name: "Commerce" },
    ],
    subjects: [
      { id: "eng", name: "English", stream: "all" },
      { id: "phy", name: "Physics", stream: ["med", "nmed"] },
      { id: "chem", name: "Chemistry", stream: ["med", "nmed"] },
      { id: "bio", name: "Biology", stream: ["med"] },
      { id: "math", name: "Mathematics", stream: ["nmed"] },
      { id: "hist", name: "History", stream: ["arts"] },
      { id: "pol", name: "Political Science", stream: ["arts"] },
      { id: "eco", name: "Economics", stream: ["arts", "com"] },
      { id: "acc", name: "Accountancy", stream: ["com"] },
      { id: "bst", name: "Business Studies", stream: ["com"] },
    ],
    notes: [
      ...chapters("11", "eng", "kehb1", [
        "The Portrait of a Lady",
        "We're Not Afraid to Die… if We Can All Be Together",
        "Discovering Tut: the Saga Continues",
        "The Ailing Planet: the Green Movement's Role",
        "The Adventure",
        "Silk Road",
        "The Summer of the Beautiful White Horse",
        "The Address",
      ]),
      { id: "11-phy-1", subject: "phy", chapter: "1", title: "Units and Measurements", ...ncert("keph101") },
      { id: "11-phy-2", subject: "phy", chapter: "2", title: "Motion in a Straight Line", ...ncert("keph102") },
      { id: "11-phy-3", subject: "phy", chapter: "3", title: "Motion in a Plane", ...ncert("keph103") },
      { id: "11-phy-4", subject: "phy", chapter: "4", title: "Laws of Motion", ...ncert("keph104") },
      { id: "11-phy-5", subject: "phy", chapter: "5", title: "Work, Energy and Power", ...ncert("keph105") },
      { id: "11-phy-6", subject: "phy", chapter: "6", title: "System of Particles and Rotational Motion", ...ncert("keph106") },
      { id: "11-phy-7", subject: "phy", chapter: "7", title: "Gravitation", ...ncert("keph107") },
      { id: "11-phy-8", subject: "phy", chapter: "8", title: "Mechanical Properties of Solids", ...ncert("keph201") },
      { id: "11-phy-9", subject: "phy", chapter: "9", title: "Mechanical Properties of Fluids", ...ncert("keph202") },
      { id: "11-phy-10", subject: "phy", chapter: "10", title: "Thermal Properties of Matter", ...ncert("keph203") },
      { id: "11-phy-11", subject: "phy", chapter: "11", title: "Thermodynamics", ...ncert("keph204") },
      { id: "11-phy-12", subject: "phy", chapter: "12", title: "Kinetic Theory", ...ncert("keph205") },
      { id: "11-phy-13", subject: "phy", chapter: "13", title: "Oscillations", ...ncert("keph206") },
      { id: "11-phy-14", subject: "phy", chapter: "14", title: "Waves", ...ncert("keph207") },
      { id: "11-chem-1", subject: "chem", chapter: "1", title: "Some Basic Concepts of Chemistry", ...ncert("kech101") },
      { id: "11-chem-2", subject: "chem", chapter: "2", title: "Structure of Atom", ...ncert("kech102") },
      { id: "11-chem-3", subject: "chem", chapter: "3", title: "Classification of Elements and Periodicity", ...ncert("kech103") },
      { id: "11-chem-4", subject: "chem", chapter: "4", title: "Chemical Bonding and Molecular Structure", ...ncert("kech104") },
      { id: "11-chem-5", subject: "chem", chapter: "5", title: "Thermodynamics", ...ncert("kech105") },
      { id: "11-chem-6", subject: "chem", chapter: "6", title: "Equilibrium", ...ncert("kech106") },
      { id: "11-chem-7", subject: "chem", chapter: "7", title: "Redox Reactions", ...ncert("kech201") },
      { id: "11-chem-8", subject: "chem", chapter: "8", title: "Organic Chemistry — Some Basic Principles and Techniques", ...ncert("kech202") },
      { id: "11-chem-9", subject: "chem", chapter: "9", title: "Hydrocarbons", ...ncert("kech203") },
      ...chapters("11", "bio", "kebo1", [
        "The Living World",
        "Biological Classification",
        "Plant Kingdom",
        "Animal Kingdom",
        "Morphology of Flowering Plants",
        "Anatomy of Flowering Plants",
        "Structural Organisation in Animals",
        "Cell: The Unit of Life",
        "Biomolecules",
        "Cell Cycle and Cell Division",
        "Photosynthesis in Higher Plants",
        "Respiration in Plants",
        "Plant Growth and Development",
        "Breathing and Exchange of Gases",
        "Body Fluids and Circulation",
        "Excretory Products and their Elimination",
        "Locomotion and Movement",
        "Neural Control and Coordination",
        "Chemical Coordination and Integration",
      ]),
      ...chapters("11", "math", "kemh1", [
        "Sets",
        "Relations and Functions",
        "Trigonometric Functions",
        "Complex Numbers and Quadratic Equations",
        "Linear Inequalities",
        "Permutations and Combinations",
        "Binomial Theorem",
        "Sequences and Series",
        "Straight Lines",
        "Conic Sections",
        "Introduction to Three Dimensional Geometry",
        "Limits and Derivatives",
        "Statistics",
        "Probability",
      ]),
      ...chapters("11", "hist", "kehs1", [
        "From the Beginning of Time",
        "Writing and City Life",
        "An Empire Across Three Continents",
        "The Central Islamic Lands",
        "Nomadic Empires",
        "The Three Orders",
        "Changing Cultural Traditions",
        "Confrontation of Cultures",
        "The Industrial Revolution",
        "Displacing Indigenous Peoples",
        "Paths to Modernisation",
      ]),
      ...chapters("11", "pol", "keps1", [
        "Constitution: Why and How?",
        "Rights in the Indian Constitution",
        "Election and Representation",
        "Executive",
        "Legislature",
        "Judiciary",
        "Federalism",
        "Local Governments",
        "Constitution as a Living Document",
        "The Philosophy of the Constitution",
      ]),
      ...chapters("11", "eco", "keec1", [
        "Indian Economy on the Eve of Independence",
        "Indian Economy 1950–1990",
        "Liberalisation, Privatisation and Globalisation",
        "Poverty",
        "Human Capital Formation in India",
        "Rural Development",
        "Employment: Growth, Informalisation and Other Issues",
        "Infrastructure",
        "Environment and Sustainable Development",
        "Comparative Development Experiences of India and its Neighbours",
      ]),
      ...chapters("11", "acc", "keac1", [
        "Introduction to Accounting",
        "Theory Base of Accounting",
        "Recording of Transactions — I",
        "Recording of Transactions — II",
        "Bank Reconciliation Statement",
        "Trial Balance and Rectification of Errors",
        "Depreciation, Provisions and Reserves",
        "Bills of Exchange",
      ]),
      ...chapters("11", "bst", "kebs1", [
        "Nature and Purpose of Business",
        "Forms of Business Organisation",
        "Private, Public and Global Enterprises",
        "Business Services",
        "Emerging Modes of Business",
        "Social Responsibilities of Business and Business Ethics",
        "Formation of a Company",
        "Sources of Business Finance",
        "Small Business and Entrepreneurship",
        "Internal Trade",
        "International Business",
      ]),
    ],
    papers: [
      { id: "11-eng-mtp", subject: "eng", title: "General English Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MPT Gen English 11th.pdf") },
      { id: "11-phy-mtp", subject: "phy", title: "Physics Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Physics 11th.pdf") },
      { id: "11-chem-mtp", subject: "chem", title: "Chemistry Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Chemistry  11th.pdf") },
      { id: "11-bio-bot", subject: "bio", title: "Botany Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Botany 11th.pdf") },
      { id: "11-bio-zoo", subject: "bio", title: "Zoology Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MPT Zoology 11th.pdf") },
      { id: "11-math-mtp", subject: "math", title: "Mathematics Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MPT Maths 11th.pdf") },
      { id: "11-hist-mtp", subject: "hist", title: "History Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MPT History 11th.pdf") },
      { id: "11-pol-mtp", subject: "pol", title: "Political Science Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MPT Political Science 11th.pdf") },
      { id: "11-eco-mtp", subject: "eco", title: "Economics Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Economics 11th.pdf") },
      { id: "11-acc-mtp", subject: "acc", title: "Accountancy Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Accountancy 11th.pdf") },
      { id: "11-bst-mtp", subject: "bst", title: "Business Studies Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Business Studies 11th.pdf") },
    ],
    books: [
      { id: "11-eng-tb", subject: "eng", title: "Hornbill", kind: "Textbook", ...ncertBook("kehb1=0-8", "kehb101") },
      { id: "11-phy-tb", subject: "phy", title: "Physics Part I & II", kind: "Textbook", ...ncertBook("keph1=0-7", "keph101") },
      { id: "11-chem-tb", subject: "chem", title: "Chemistry Part I & II", kind: "Textbook", ...ncertBook("kech1=0-6", "kech101") },
      { id: "11-bio-tb", subject: "bio", title: "Biology Class 11", kind: "Textbook", ...ncertBook("kebo1=0-19", "kebo101") },
      { id: "11-math-tb", subject: "math", title: "Mathematics Class 11", kind: "Textbook", ...ncertBook("kemh1=0-14", "kemh101") },
      { id: "11-hist-tb", subject: "hist", title: "Themes in World History", kind: "Textbook", ...ncertBook("kehs1=0-11", "kehs101") },
      { id: "11-pol-tb", subject: "pol", title: "Indian Constitution at Work", kind: "Textbook", ...ncertBook("keps1=0-10", "keps101") },
      { id: "11-eco-tb", subject: "eco", title: "Indian Economic Development", kind: "Textbook", ...ncertBook("keec1=0-10", "keec101") },
      { id: "11-acc-tb", subject: "acc", title: "Financial Accounting Part I", kind: "Textbook", ...ncertBook("keac1=0-8", "keac101") },
      { id: "11-bst-tb", subject: "bst", title: "Business Studies Class 11", kind: "Textbook", ...ncertBook("kebs1=0-11", "kebs101") },
    ],
  },

  "12": {
    label: "Class 12th",
    streams: [
      { id: "med", name: "Medical" },
      { id: "nmed", name: "Non-Medical" },
      { id: "arts", name: "Arts" },
      { id: "com", name: "Commerce" },
    ],
    subjects: [
      { id: "eng", name: "English", stream: "all" },
      { id: "phy", name: "Physics", stream: ["med", "nmed"] },
      { id: "chem", name: "Chemistry", stream: ["med", "nmed"] },
      { id: "bio", name: "Biology", stream: ["med"] },
      { id: "math", name: "Mathematics", stream: ["nmed"] },
      { id: "hist", name: "History", stream: ["arts"] },
      { id: "pol", name: "Political Science", stream: ["arts"] },
      { id: "eco", name: "Economics", stream: ["arts", "com"] },
      { id: "acc", name: "Accountancy", stream: ["com"] },
      { id: "bst", name: "Business Studies", stream: ["com"] },
    ],
    notes: [
      ...chapters("12", "eng", "lefl1", [
        "The Last Lesson",
        "Lost Spring",
        "Deep Water",
        "The Rattrap",
        "Indigo",
        "Poets and Pancakes",
        "The Interview",
        "Going Places",
      ]),
      { id: "12-phy-1", subject: "phy", chapter: "1", title: "Electric Charges and Fields", ...ncert("leph101") },
      { id: "12-phy-2", subject: "phy", chapter: "2", title: "Electrostatic Potential and Capacitance", ...ncert("leph102") },
      { id: "12-phy-3", subject: "phy", chapter: "3", title: "Current Electricity", ...ncert("leph103") },
      { id: "12-phy-4", subject: "phy", chapter: "4", title: "Moving Charges and Magnetism", ...ncert("leph104") },
      { id: "12-phy-5", subject: "phy", chapter: "5", title: "Magnetism and Matter", ...ncert("leph105") },
      { id: "12-phy-6", subject: "phy", chapter: "6", title: "Electromagnetic Induction", ...ncert("leph106") },
      { id: "12-phy-7", subject: "phy", chapter: "7", title: "Alternating Current", ...ncert("leph107") },
      { id: "12-phy-8", subject: "phy", chapter: "8", title: "Electromagnetic Waves", ...ncert("leph108") },
      { id: "12-phy-9", subject: "phy", chapter: "9", title: "Ray Optics and Optical Instruments", ...ncert("leph201") },
      { id: "12-phy-10", subject: "phy", chapter: "10", title: "Wave Optics", ...ncert("leph202") },
      { id: "12-phy-11", subject: "phy", chapter: "11", title: "Dual Nature of Radiation and Matter", ...ncert("leph203") },
      { id: "12-phy-12", subject: "phy", chapter: "12", title: "Atoms", ...ncert("leph204") },
      { id: "12-phy-13", subject: "phy", chapter: "13", title: "Nuclei", ...ncert("leph205") },
      { id: "12-phy-14", subject: "phy", chapter: "14", title: "Semiconductor Electronics", ...ncert("leph206") },
      { id: "12-chem-1", subject: "chem", chapter: "1", title: "Solutions", ...ncert("lech101") },
      { id: "12-chem-2", subject: "chem", chapter: "2", title: "Electrochemistry", ...ncert("lech102") },
      { id: "12-chem-3", subject: "chem", chapter: "3", title: "Chemical Kinetics", ...ncert("lech103") },
      { id: "12-chem-4", subject: "chem", chapter: "4", title: "The d- and f-Block Elements", ...ncert("lech104") },
      { id: "12-chem-5", subject: "chem", chapter: "5", title: "Coordination Compounds", ...ncert("lech105") },
      { id: "12-chem-6", subject: "chem", chapter: "6", title: "Haloalkanes and Haloarenes", ...ncert("lech201") },
      { id: "12-chem-7", subject: "chem", chapter: "7", title: "Alcohols, Phenols and Ethers", ...ncert("lech202") },
      { id: "12-chem-8", subject: "chem", chapter: "8", title: "Aldehydes, Ketones and Carboxylic Acids", ...ncert("lech203") },
      { id: "12-chem-9", subject: "chem", chapter: "9", title: "Amines", ...ncert("lech204") },
      { id: "12-chem-10", subject: "chem", chapter: "10", title: "Biomolecules", ...ncert("lech205") },
      ...chapters("12", "bio", "lebo1", [
        "Sexual Reproduction in Flowering Plants",
        "Human Reproduction",
        "Reproductive Health",
        "Principles of Inheritance and Variation",
        "Molecular Basis of Inheritance",
        "Evolution",
        "Human Health and Disease",
        "Microbes in Human Welfare",
        "Biotechnology: Principles and Processes",
        "Biotechnology and its Applications",
        "Organisms and Populations",
        "Ecosystem",
        "Biodiversity and Conservation",
      ]),
      { id: "12-math-1", subject: "math", chapter: "1", title: "Relations and Functions", ...ncert("lemh101") },
      { id: "12-math-2", subject: "math", chapter: "2", title: "Inverse Trigonometric Functions", ...ncert("lemh102") },
      { id: "12-math-3", subject: "math", chapter: "3", title: "Matrices", ...ncert("lemh103") },
      { id: "12-math-4", subject: "math", chapter: "4", title: "Determinants", ...ncert("lemh104") },
      { id: "12-math-5", subject: "math", chapter: "5", title: "Continuity and Differentiability", ...ncert("lemh105") },
      { id: "12-math-6", subject: "math", chapter: "6", title: "Application of Derivatives", ...ncert("lemh106") },
      { id: "12-math-7", subject: "math", chapter: "7", title: "Integrals", ...ncert("lemh201") },
      { id: "12-math-8", subject: "math", chapter: "8", title: "Application of Integrals", ...ncert("lemh202") },
      { id: "12-math-9", subject: "math", chapter: "9", title: "Differential Equations", ...ncert("lemh203") },
      { id: "12-math-10", subject: "math", chapter: "10", title: "Vector Algebra", ...ncert("lemh204") },
      { id: "12-math-11", subject: "math", chapter: "11", title: "Three Dimensional Geometry", ...ncert("lemh205") },
      { id: "12-math-12", subject: "math", chapter: "12", title: "Linear Programming", ...ncert("lemh206") },
      { id: "12-math-13", subject: "math", chapter: "13", title: "Probability", ...ncert("lemh207") },
      { id: "12-hist-1", subject: "hist", chapter: "1", title: "Bricks, Beads and Bones", ...ncert("lehs101") },
      { id: "12-hist-2", subject: "hist", chapter: "2", title: "Kings, Farmers and Towns", ...ncert("lehs102") },
      { id: "12-hist-3", subject: "hist", chapter: "3", title: "Kinship, Caste and Class", ...ncert("lehs103") },
      { id: "12-hist-4", subject: "hist", chapter: "4", title: "Thinkers, Beliefs and Buildings", ...ncert("lehs104") },
      { id: "12-hist-5", subject: "hist", chapter: "5", title: "Through the Eyes of Travellers", ...ncert("lehs201") },
      { id: "12-hist-6", subject: "hist", chapter: "6", title: "Bhakti-Sufi Traditions", ...ncert("lehs202") },
      { id: "12-hist-7", subject: "hist", chapter: "7", title: "An Imperial Capital: Vijayanagara", ...ncert("lehs203") },
      { id: "12-hist-8", subject: "hist", chapter: "8", title: "Peasants, Zamindars and the State", ...ncert("lehs204") },
      { id: "12-hist-9", subject: "hist", chapter: "9", title: "Kings and Chronicles", ...ncert("lehs205") },
      { id: "12-hist-10", subject: "hist", chapter: "10", title: "Colonialism and the Countryside", ...ncert("lehs301") },
      { id: "12-hist-11", subject: "hist", chapter: "11", title: "Rebels and the Raj", ...ncert("lehs302") },
      { id: "12-hist-12", subject: "hist", chapter: "12", title: "Mahatma Gandhi and the Nationalist Movement", ...ncert("lehs303") },
      { id: "12-hist-13", subject: "hist", chapter: "13", title: "Framing the Constitution", ...ncert("lehs304") },
      ...chapters("12", "pol", "leps1", [
        "The End of Bipolarity",
        "Contemporary Centres of Power",
        "Contemporary South Asia",
        "International Organisations",
        "Security in the Contemporary World",
        "Environment and Natural Resources",
        "Globalisation",
      ]),
      ...chapters("12", "eco", "leec1", [
        "Introduction",
        "National Income Accounting",
        "Money and Banking",
        "Determination of Income and Employment",
        "Government Budget and the Economy",
        "Open Economy Macroeconomics",
      ]),
      ...chapters("12", "acc", "leac1", [
        "Accounting for Partnership: Basic Concepts",
        "Reconstitution of a Partnership Firm — Admission",
        "Reconstitution of a Partnership Firm — Retirement/Death",
        "Dissolution of Partnership Firm",
        "Accounting for Share Capital",
      ]),
      { id: "12-bst-1", subject: "bst", chapter: "1", title: "Nature and Significance of Management", ...ncert("lebs101") },
      { id: "12-bst-2", subject: "bst", chapter: "2", title: "Principles of Management", ...ncert("lebs102") },
      { id: "12-bst-3", subject: "bst", chapter: "3", title: "Business Environment", ...ncert("lebs103") },
      { id: "12-bst-4", subject: "bst", chapter: "4", title: "Planning", ...ncert("lebs104") },
      { id: "12-bst-5", subject: "bst", chapter: "5", title: "Organising", ...ncert("lebs105") },
      { id: "12-bst-6", subject: "bst", chapter: "6", title: "Staffing", ...ncert("lebs106") },
      { id: "12-bst-7", subject: "bst", chapter: "7", title: "Directing", ...ncert("lebs107") },
      { id: "12-bst-8", subject: "bst", chapter: "8", title: "Controlling", ...ncert("lebs108") },
      { id: "12-bst-9", subject: "bst", chapter: "9", title: "Financial Management", ...ncert("lebs201") },
      { id: "12-bst-10", subject: "bst", chapter: "10", title: "Marketing", ...ncert("lebs202") },
      { id: "12-bst-11", subject: "bst", chapter: "11", title: "Consumer Protection", ...ncert("lebs203") },
    ],
    papers: [
      { id: "12-eng-mtp", subject: "eng", title: "English Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP English 12th.pdf") },
      { id: "12-phy-mtp", subject: "phy", title: "Physics Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Physics 12th.pdf") },
      { id: "12-chem-mtp", subject: "chem", title: "Chemistry Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP  Chemistry 12th.pdf") },
      { id: "12-bio-bot", subject: "bio", title: "Botany Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Botany 12th.pdf") },
      { id: "12-bio-zoo", subject: "bio", title: "Zoology Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Zoology 12th.pdf") },
      { id: "12-math-mtp", subject: "math", title: "Mathematics Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Mathematics 12th.pdf") },
      { id: "12-hist-mtp", subject: "hist", title: "History Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP History 12th.pdf") },
      { id: "12-pol-mtp", subject: "pol", title: "Political Science Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Political Science 12th.pdf") },
      { id: "12-eco-mtp", subject: "eco", title: "Economics Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("Model paper Economics 12th.pdf") },
      { id: "12-acc-mtp", subject: "acc", title: "Accountancy Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Accountacy 12th.pdf") },
      { id: "12-bst-mtp", subject: "bst", title: "Business Studies Model Test Paper", year: "JKBOSE", kind: "Model paper", ...jkbosePaper("MTP Business Studies  12th.pdf") },
    ],
    books: [
      { id: "12-eng-tb", subject: "eng", title: "Flamingo", kind: "Textbook", ...ncertBook("lefl1=0-8", "lefl101") },
      { id: "12-eng-sup", subject: "eng", title: "Vistas", kind: "Supplementary", ...ncertBook("levt1=0-8", "levt101") },
      { id: "12-phy-tb", subject: "phy", title: "Physics Part I & II", kind: "Textbook", ...ncertBook("leph1=0-8", "leph101") },
      { id: "12-chem-tb", subject: "chem", title: "Chemistry Part I & II", kind: "Textbook", ...ncertBook("lech1=0-5", "lech101") },
      { id: "12-bio-tb", subject: "bio", title: "Biology Class 12", kind: "Textbook", ...ncertBook("lebo1=0-13", "lebo101") },
      { id: "12-math-tb", subject: "math", title: "Mathematics Part I & II", kind: "Textbook", ...ncertBook("lemh1=0-6", "lemh101") },
      { id: "12-hist-tb", subject: "hist", title: "Themes in Indian History I–III", kind: "Textbook", ...ncertBook("lehs1=0-4", "lehs101") },
      { id: "12-pol-tb", subject: "pol", title: "Contemporary World Politics", kind: "Textbook", ...ncertBook("leps1=0-7", "leps101") },
      { id: "12-eco-tb", subject: "eco", title: "Introductory Macroeconomics", kind: "Textbook", ...ncertBook("leec1=0-6", "leec101") },
      { id: "12-acc-tb", subject: "acc", title: "Accountancy Part I", kind: "Textbook", ...ncertBook("leac1=0-5", "leac101") },
      { id: "12-bst-tb", subject: "bst", title: "Business Studies Part I & II", kind: "Textbook", ...ncertBook("lebs1=0-8", "lebs101") },
    ],
  },
};
