/* AQIBS WEB2 — study catalogue
   Swap viewUrl / downloadUrl on any item with a real PDF later.
   Structure:
     STUDY_DATA[classId].streams?  → 11/12 only
     STUDY_DATA[classId].subjects  → { id, name, stream? }
     STUDY_DATA[classId].notes     → { id, subject, chapter, title, viewUrl, downloadUrl }
     STUDY_DATA[classId].papers    → { id, subject, title, year, kind, viewUrl, downloadUrl }
     STUDY_DATA[classId].books     → { id, subject, title, kind, viewUrl, downloadUrl }
*/
const PLACEHOLDER = "";

const STUDY_DATA = {
  "10": {
    label: "Class 10th",
    streams: null,
    subjects: [
      { id: "eng", name: "English" },
      { id: "math", name: "Mathematics" },
      { id: "sci", name: "Science" },
      { id: "sst", name: "Social Science" },
      { id: "urd", name: "Urdu" },
      { id: "hin", name: "Hindi" },
    ],
    notes: [
      { id: "10-eng-1", subject: "eng", chapter: "1", title: "A Letter to God" },
      { id: "10-eng-2", subject: "eng", chapter: "2", title: "Nelson Mandela: Long Walk to Freedom" },
      { id: "10-eng-3", subject: "eng", chapter: "3", title: "Two Stories about Flying" },
      { id: "10-eng-4", subject: "eng", chapter: "4", title: "From the Diary of Anne Frank" },
      { id: "10-eng-5", subject: "eng", chapter: "5", title: "Glimpses of India" },
      { id: "10-math-1", subject: "math", chapter: "1", title: "Real Numbers" },
      { id: "10-math-2", subject: "math", chapter: "2", title: "Polynomials" },
      { id: "10-math-3", subject: "math", chapter: "3", title: "Pair of Linear Equations in Two Variables" },
      { id: "10-math-4", subject: "math", chapter: "4", title: "Quadratic Equations" },
      { id: "10-math-5", subject: "math", chapter: "5", title: "Arithmetic Progressions" },
      { id: "10-math-6", subject: "math", chapter: "6", title: "Triangles" },
      { id: "10-sci-1", subject: "sci", chapter: "1", title: "Chemical Reactions and Equations" },
      { id: "10-sci-2", subject: "sci", chapter: "2", title: "Acids, Bases and Salts" },
      { id: "10-sci-3", subject: "sci", chapter: "3", title: "Metals and Non-metals" },
      { id: "10-sci-4", subject: "sci", chapter: "4", title: "Carbon and its Compounds" },
      { id: "10-sci-5", subject: "sci", chapter: "5", title: "Life Processes" },
      { id: "10-sci-6", subject: "sci", chapter: "6", title: "Control and Coordination" },
      { id: "10-sci-7", subject: "sci", chapter: "7", title: "How do Organisms Reproduce?" },
      { id: "10-sci-8", subject: "sci", chapter: "8", title: "Heredity" },
      { id: "10-sci-9", subject: "sci", chapter: "9", title: "Light — Reflection and Refraction" },
      { id: "10-sci-10", subject: "sci", chapter: "10", title: "The Human Eye and the Colourful World" },
      { id: "10-sci-11", subject: "sci", chapter: "11", title: "Electricity" },
      { id: "10-sci-12", subject: "sci", chapter: "12", title: "Magnetic Effects of Electric Current" },
      { id: "10-sst-1", subject: "sst", chapter: "1", title: "The Rise of Nationalism in Europe" },
      { id: "10-sst-2", subject: "sst", chapter: "2", title: "Nationalism in India" },
      { id: "10-sst-3", subject: "sst", chapter: "3", title: "Resources and Development" },
      { id: "10-sst-4", subject: "sst", chapter: "4", title: "Agriculture" },
      { id: "10-sst-5", subject: "sst", chapter: "5", title: "Power Sharing" },
      { id: "10-sst-6", subject: "sst", chapter: "6", title: "Federalism" },
      { id: "10-urd-1", subject: "urd", chapter: "1", title: "Nazeer Akbarabadi" },
      { id: "10-urd-2", subject: "urd", chapter: "2", title: "Mirza Ghalib" },
      { id: "10-hin-1", subject: "hin", chapter: "1", title: "सूरदास" },
      { id: "10-hin-2", subject: "hin", chapter: "2", title: "तुलसीदास" },
    ],
    papers: [
      { id: "10-eng-py-24", subject: "eng", title: "English Annual", year: "2024", kind: "Board paper" },
      { id: "10-eng-py-23", subject: "eng", title: "English Annual", year: "2023", kind: "Board paper" },
      { id: "10-eng-mp", subject: "eng", title: "English Model Paper", year: "2025", kind: "Model paper" },
      { id: "10-math-py-24", subject: "math", title: "Mathematics Annual", year: "2024", kind: "Board paper" },
      { id: "10-math-py-23", subject: "math", title: "Mathematics Annual", year: "2023", kind: "Board paper" },
      { id: "10-math-mp", subject: "math", title: "Mathematics Model Paper", year: "2025", kind: "Model paper" },
      { id: "10-sci-py-24", subject: "sci", title: "Science Annual", year: "2024", kind: "Board paper" },
      { id: "10-sci-py-23", subject: "sci", title: "Science Annual", year: "2023", kind: "Board paper" },
      { id: "10-sci-mp", subject: "sci", title: "Science Model Paper", year: "2025", kind: "Model paper" },
      { id: "10-sst-py-24", subject: "sst", title: "Social Science Annual", year: "2024", kind: "Board paper" },
      { id: "10-sst-mp", subject: "sst", title: "Social Science Model Paper", year: "2025", kind: "Model paper" },
      { id: "10-urd-py-24", subject: "urd", title: "Urdu Annual", year: "2024", kind: "Board paper" },
      { id: "10-hin-py-24", subject: "hin", title: "Hindi Annual", year: "2024", kind: "Board paper" },
    ],
    books: [
      { id: "10-eng-tb", subject: "eng", title: "First Flight", kind: "Textbook" },
      { id: "10-eng-sup", subject: "eng", title: "Footprints without Feet", kind: "Supplementary" },
      { id: "10-math-tb", subject: "math", title: "Mathematics Class 10", kind: "Textbook" },
      { id: "10-sci-tb", subject: "sci", title: "Science Class 10", kind: "Textbook" },
      { id: "10-sst-h", subject: "sst", title: "India and the Contemporary World II", kind: "History" },
      { id: "10-sst-g", subject: "sst", title: "Contemporary India II", kind: "Geography" },
      { id: "10-sst-p", subject: "sst", title: "Democratic Politics II", kind: "Political Science" },
      { id: "10-sst-e", subject: "sst", title: "Understanding Economic Development", kind: "Economics" },
      { id: "10-urd-tb", subject: "urd", title: "Urdu Class 10 Reader", kind: "Textbook" },
      { id: "10-hin-tb", subject: "hin", title: "क्षितिज भाग 2", kind: "Textbook" },
    ],
  },

  "11": {
    label: "Class 11th",
    streams: [
      { id: "med", name: "Medical" },
      { id: "nmed", name: "Non-Medical" },
      { id: "arts", name: "Arts" },
      { id: "com", name: "Commerce" },
    ],
    subjects: [
      { id: "eng", name: "English", stream: "all" },
      { id: "phy", name: "Physics", stream: ["med", "nmed"] },
      { id: "chem", name: "Chemistry", stream: ["med", "nmed"] },
      { id: "bio", name: "Biology", stream: ["med"] },
      { id: "math", name: "Mathematics", stream: ["nmed"] },
      { id: "hist", name: "History", stream: ["arts"] },
      { id: "pol", name: "Political Science", stream: ["arts"] },
      { id: "eco", name: "Economics", stream: ["arts", "com"] },
      { id: "acc", name: "Accountancy", stream: ["com"] },
      { id: "bst", name: "Business Studies", stream: ["com"] },
    ],
    notes: [
      { id: "11-eng-1", subject: "eng", chapter: "1", title: "The Portrait of a Lady" },
      { id: "11-eng-2", subject: "eng", chapter: "2", title: "We're Not Afraid to Die…" },
      { id: "11-eng-3", subject: "eng", chapter: "3", title: "Discovering Tut: the Saga Continues" },
      { id: "11-phy-1", subject: "phy", chapter: "1", title: "Units and Measurements" },
      { id: "11-phy-2", subject: "phy", chapter: "2", title: "Motion in a Straight Line" },
      { id: "11-phy-3", subject: "phy", chapter: "3", title: "Motion in a Plane" },
      { id: "11-phy-4", subject: "phy", chapter: "4", title: "Laws of Motion" },
      { id: "11-phy-5", subject: "phy", chapter: "5", title: "Work, Energy and Power" },
      { id: "11-chem-1", subject: "chem", chapter: "1", title: "Some Basic Concepts of Chemistry" },
      { id: "11-chem-2", subject: "chem", chapter: "2", title: "Structure of Atom" },
      { id: "11-chem-3", subject: "chem", chapter: "3", title: "Classification of Elements and Periodicity" },
      { id: "11-chem-4", subject: "chem", chapter: "4", title: "Chemical Bonding and Molecular Structure" },
      { id: "11-bio-1", subject: "bio", chapter: "1", title: "The Living World" },
      { id: "11-bio-2", subject: "bio", chapter: "2", title: "Biological Classification" },
      { id: "11-bio-3", subject: "bio", chapter: "3", title: "Plant Kingdom" },
      { id: "11-bio-4", subject: "bio", chapter: "4", title: "Animal Kingdom" },
      { id: "11-bio-5", subject: "bio", chapter: "5", title: "Morphology of Flowering Plants" },
      { id: "11-math-1", subject: "math", chapter: "1", title: "Sets" },
      { id: "11-math-2", subject: "math", chapter: "2", title: "Relations and Functions" },
      { id: "11-math-3", subject: "math", chapter: "3", title: "Trigonometric Functions" },
      { id: "11-math-4", subject: "math", chapter: "4", title: "Complex Numbers and Quadratic Equations" },
      { id: "11-hist-1", subject: "hist", chapter: "1", title: "From the Beginning of Time" },
      { id: "11-hist-2", subject: "hist", chapter: "2", title: "Writing and City Life" },
      { id: "11-pol-1", subject: "pol", chapter: "1", title: "Constitution: Why and How?" },
      { id: "11-pol-2", subject: "pol", chapter: "2", title: "Rights in the Indian Constitution" },
      { id: "11-eco-1", subject: "eco", chapter: "1", title: "Indian Economy on the Eve of Independence" },
      { id: "11-eco-2", subject: "eco", chapter: "2", title: "Indian Economy 1950–1990" },
      { id: "11-acc-1", subject: "acc", chapter: "1", title: "Introduction to Accounting" },
      { id: "11-acc-2", subject: "acc", chapter: "2", title: "Theory Base of Accounting" },
      { id: "11-bst-1", subject: "bst", chapter: "1", title: "Nature and Purpose of Business" },
      { id: "11-bst-2", subject: "bst", chapter: "2", title: "Forms of Business Organisation" },
    ],
    papers: [
      { id: "11-eng-py-24", subject: "eng", title: "English Annual", year: "2024", kind: "Board paper" },
      { id: "11-phy-py-24", subject: "phy", title: "Physics Annual", year: "2024", kind: "Board paper" },
      { id: "11-phy-mp", subject: "phy", title: "Physics Model Paper", year: "2025", kind: "Model paper" },
      { id: "11-chem-py-24", subject: "chem", title: "Chemistry Annual", year: "2024", kind: "Board paper" },
      { id: "11-bio-py-24", subject: "bio", title: "Biology Annual", year: "2024", kind: "Board paper" },
      { id: "11-math-py-24", subject: "math", title: "Mathematics Annual", year: "2024", kind: "Board paper" },
      { id: "11-hist-py-24", subject: "hist", title: "History Annual", year: "2024", kind: "Board paper" },
      { id: "11-pol-py-24", subject: "pol", title: "Political Science Annual", year: "2024", kind: "Board paper" },
      { id: "11-eco-py-24", subject: "eco", title: "Economics Annual", year: "2024", kind: "Board paper" },
      { id: "11-acc-py-24", subject: "acc", title: "Accountancy Annual", year: "2024", kind: "Board paper" },
      { id: "11-bst-py-24", subject: "bst", title: "Business Studies Annual", year: "2024", kind: "Board paper" },
    ],
    books: [
      { id: "11-eng-tb", subject: "eng", title: "Hornbill", kind: "Textbook" },
      { id: "11-eng-sup", subject: "eng", title: "Snapshots", kind: "Supplementary" },
      { id: "11-phy-tb", subject: "phy", title: "Physics Part I & II", kind: "Textbook" },
      { id: "11-chem-tb", subject: "chem", title: "Chemistry Part I & II", kind: "Textbook" },
      { id: "11-bio-tb", subject: "bio", title: "Biology Class 11", kind: "Textbook" },
      { id: "11-math-tb", subject: "math", title: "Mathematics Class 11", kind: "Textbook" },
      { id: "11-hist-tb", subject: "hist", title: "Themes in World History", kind: "Textbook" },
      { id: "11-pol-tb", subject: "pol", title: "Indian Constitution at Work", kind: "Textbook" },
      { id: "11-eco-tb", subject: "eco", title: "Indian Economic Development", kind: "Textbook" },
      { id: "11-acc-tb", subject: "acc", title: "Financial Accounting Part I", kind: "Textbook" },
      { id: "11-bst-tb", subject: "bst", title: "Business Studies Class 11", kind: "Textbook" },
    ],
  },

  "12": {
    label: "Class 12th",
    streams: [
      { id: "med", name: "Medical" },
      { id: "nmed", name: "Non-Medical" },
      { id: "arts", name: "Arts" },
      { id: "com", name: "Commerce" },
    ],
    subjects: [
      { id: "eng", name: "English", stream: "all" },
      { id: "phy", name: "Physics", stream: ["med", "nmed"] },
      { id: "chem", name: "Chemistry", stream: ["med", "nmed"] },
      { id: "bio", name: "Biology", stream: ["med"] },
      { id: "math", name: "Mathematics", stream: ["nmed"] },
      { id: "hist", name: "History", stream: ["arts"] },
      { id: "pol", name: "Political Science", stream: ["arts"] },
      { id: "eco", name: "Economics", stream: ["arts", "com"] },
      { id: "acc", name: "Accountancy", stream: ["com"] },
      { id: "bst", name: "Business Studies", stream: ["com"] },
    ],
    notes: [
      { id: "12-eng-1", subject: "eng", chapter: "1", title: "The Last Lesson" },
      { id: "12-eng-2", subject: "eng", chapter: "2", title: "Lost Spring" },
      { id: "12-eng-3", subject: "eng", chapter: "3", title: "Deep Water" },
      { id: "12-eng-4", subject: "eng", chapter: "4", title: "The Rattrap" },
      { id: "12-phy-1", subject: "phy", chapter: "1", title: "Electric Charges and Fields" },
      { id: "12-phy-2", subject: "phy", chapter: "2", title: "Electrostatic Potential and Capacitance" },
      { id: "12-phy-3", subject: "phy", chapter: "3", title: "Current Electricity" },
      { id: "12-phy-4", subject: "phy", chapter: "4", title: "Moving Charges and Magnetism" },
      { id: "12-phy-5", subject: "phy", chapter: "5", title: "Electromagnetic Induction" },
      { id: "12-chem-1", subject: "chem", chapter: "1", title: "Solutions" },
      { id: "12-chem-2", subject: "chem", chapter: "2", title: "Electrochemistry" },
      { id: "12-chem-3", subject: "chem", chapter: "3", title: "Chemical Kinetics" },
      { id: "12-chem-4", subject: "chem", chapter: "4", title: "d- and f-Block Elements" },
      { id: "12-bio-1", subject: "bio", chapter: "1", title: "Sexual Reproduction in Flowering Plants" },
      { id: "12-bio-2", subject: "bio", chapter: "2", title: "Human Reproduction" },
      { id: "12-bio-3", subject: "bio", chapter: "3", title: "Principles of Inheritance and Variation" },
      { id: "12-bio-4", subject: "bio", chapter: "4", title: "Molecular Basis of Inheritance" },
      { id: "12-math-1", subject: "math", chapter: "1", title: "Relations and Functions" },
      { id: "12-math-2", subject: "math", chapter: "2", title: "Inverse Trigonometric Functions" },
      { id: "12-math-3", subject: "math", chapter: "3", title: "Matrices" },
      { id: "12-math-4", subject: "math", chapter: "4", title: "Determinants" },
      { id: "12-math-5", subject: "math", chapter: "5", title: "Continuity and Differentiability" },
      { id: "12-hist-1", subject: "hist", chapter: "1", title: "Bricks, Beads and Bones" },
      { id: "12-hist-2", subject: "hist", chapter: "2", title: "Kings, Farmers and Towns" },
      { id: "12-pol-1", subject: "pol", chapter: "1", title: "The End of Bipolarity" },
      { id: "12-pol-2", subject: "pol", chapter: "2", title: "Contemporary Centres of Power" },
      { id: "12-eco-1", subject: "eco", chapter: "1", title: "Indian Economy on the Eve of Independence" },
      { id: "12-eco-2", subject: "eco", chapter: "2", title: "Indian Economy 1950–1990" },
      { id: "12-acc-1", subject: "acc", chapter: "1", title: "Accounting for Partnership Firms" },
      { id: "12-acc-2", subject: "acc", chapter: "2", title: "Accounting for Companies" },
      { id: "12-bst-1", subject: "bst", chapter: "1", title: "Nature and Significance of Management" },
      { id: "12-bst-2", subject: "bst", chapter: "2", title: "Principles of Management" },
    ],
    papers: [
      { id: "12-eng-py-24", subject: "eng", title: "English Annual", year: "2024", kind: "Board paper" },
      { id: "12-eng-py-23", subject: "eng", title: "English Annual", year: "2023", kind: "Board paper" },
      { id: "12-phy-py-24", subject: "phy", title: "Physics Annual", year: "2024", kind: "Board paper" },
      { id: "12-phy-mp", subject: "phy", title: "Physics Model Paper", year: "2025", kind: "Model paper" },
      { id: "12-chem-py-24", subject: "chem", title: "Chemistry Annual", year: "2024", kind: "Board paper" },
      { id: "12-bio-py-24", subject: "bio", title: "Biology Annual", year: "2024", kind: "Board paper" },
      { id: "12-math-py-24", subject: "math", title: "Mathematics Annual", year: "2024", kind: "Board paper" },
      { id: "12-hist-py-24", subject: "hist", title: "History Annual", year: "2024", kind: "Board paper" },
      { id: "12-pol-py-24", subject: "pol", title: "Political Science Annual", year: "2024", kind: "Board paper" },
      { id: "12-eco-py-24", subject: "eco", title: "Economics Annual", year: "2024", kind: "Board paper" },
      { id: "12-acc-py-24", subject: "acc", title: "Accountancy Annual", year: "2024", kind: "Board paper" },
      { id: "12-bst-py-24", subject: "bst", title: "Business Studies Annual", year: "2024", kind: "Board paper" },
    ],
    books: [
      { id: "12-eng-tb", subject: "eng", title: "Flamingo", kind: "Textbook" },
      { id: "12-eng-sup", subject: "eng", title: "Vistas", kind: "Supplementary" },
      { id: "12-phy-tb", subject: "phy", title: "Physics Part I & II", kind: "Textbook" },
      { id: "12-chem-tb", subject: "chem", title: "Chemistry Part I & II", kind: "Textbook" },
      { id: "12-bio-tb", subject: "bio", title: "Biology Class 12", kind: "Textbook" },
      { id: "12-math-tb", subject: "math", title: "Mathematics Part I & II", kind: "Textbook" },
      { id: "12-hist-tb", subject: "hist", title: "Themes in Indian History", kind: "Textbook" },
      { id: "12-pol-tb", subject: "pol", title: "Contemporary World Politics", kind: "Textbook" },
      { id: "12-eco-tb", subject: "eco", title: "Introductory Macroeconomics", kind: "Textbook" },
      { id: "12-acc-tb", subject: "acc", title: "Accountancy Part I & II", kind: "Textbook" },
      { id: "12-bst-tb", subject: "bst", title: "Business Studies Part I & II", kind: "Textbook" },
    ],
  },
};

Object.values(STUDY_DATA).forEach((klass) => {
  ["notes", "papers", "books"].forEach((bucket) => {
    klass[bucket].forEach((item) => {
      if (item.viewUrl === undefined) item.viewUrl = PLACEHOLDER;
      if (item.downloadUrl === undefined) item.downloadUrl = PLACEHOLDER;
    });
  });
});
