/* AQIBS WEB2 — JKBOSE study catalogue
   Notes = official NCERT chapter PDFs (JKBOSE follows this syllabus)
   Books = official NCERT textbook readers
   Papers = official NCERT exemplar / sample paper readers + JKBOSE portal
*/
const NCERT = "https://ncert.nic.in/textbook/pdf/";
const NCERT_READ = "https://ncert.nic.in/textbook.php?";
const JKBOSE_PAPERS = "https://jkbose.nic.in/";

function ncert(code) {
  const pdf = `${NCERT}${code}.pdf`;
  return { viewUrl: pdf, downloadUrl: pdf };
}

function ncertBook(query, firstChapter) {
  return {
    viewUrl: `${NCERT_READ}${query}`,
    downloadUrl: `${NCERT}${firstChapter}.pdf`,
  };
}

const STUDY_DATA = {
  "10": {
    label: "Class 10th",
    streams: null,
    subjects: [
      { id: "eng", name: "English" },
      { id: "math", name: "Mathematics" },
      { id: "sci", name: "Science" },
      { id: "sst", name: "Social Science" },
      { id: "hin", name: "Hindi" },
    ],
    notes: [
      { id: "10-eng-1", subject: "eng", chapter: "1", title: "A Letter to God", ...ncert("jeff101") },
      { id: "10-eng-2", subject: "eng", chapter: "2", title: "Nelson Mandela: Long Walk to Freedom", ...ncert("jeff102") },
      { id: "10-eng-3", subject: "eng", chapter: "3", title: "Two Stories about Flying", ...ncert("jeff103") },
      { id: "10-eng-4", subject: "eng", chapter: "4", title: "From the Diary of Anne Frank", ...ncert("jeff104") },
      { id: "10-eng-5", subject: "eng", chapter: "5", title: "Glimpses of India", ...ncert("jeff105") },
      { id: "10-math-1", subject: "math", chapter: "1", title: "Real Numbers", ...ncert("jemh101") },
      { id: "10-math-2", subject: "math", chapter: "2", title: "Polynomials", ...ncert("jemh102") },
      { id: "10-math-3", subject: "math", chapter: "3", title: "Pair of Linear Equations in Two Variables", ...ncert("jemh103") },
      { id: "10-math-4", subject: "math", chapter: "4", title: "Quadratic Equations", ...ncert("jemh104") },
      { id: "10-math-5", subject: "math", chapter: "5", title: "Arithmetic Progressions", ...ncert("jemh105") },
      { id: "10-math-6", subject: "math", chapter: "6", title: "Triangles", ...ncert("jemh106") },
      { id: "10-sci-1", subject: "sci", chapter: "1", title: "Chemical Reactions and Equations", ...ncert("jesc101") },
      { id: "10-sci-2", subject: "sci", chapter: "2", title: "Acids, Bases and Salts", ...ncert("jesc102") },
      { id: "10-sci-3", subject: "sci", chapter: "3", title: "Metals and Non-metals", ...ncert("jesc103") },
      { id: "10-sci-4", subject: "sci", chapter: "4", title: "Carbon and its Compounds", ...ncert("jesc104") },
      { id: "10-sci-5", subject: "sci", chapter: "5", title: "Life Processes", ...ncert("jesc105") },
      { id: "10-sci-6", subject: "sci", chapter: "6", title: "Control and Coordination", ...ncert("jesc106") },
      { id: "10-sci-7", subject: "sci", chapter: "7", title: "How do Organisms Reproduce?", ...ncert("jesc107") },
      { id: "10-sci-8", subject: "sci", chapter: "8", title: "Heredity", ...ncert("jesc108") },
      { id: "10-sci-9", subject: "sci", chapter: "9", title: "Light — Reflection and Refraction", ...ncert("jesc109") },
      { id: "10-sci-10", subject: "sci", chapter: "10", title: "The Human Eye and the Colourful World", ...ncert("jesc110") },
      { id: "10-sci-11", subject: "sci", chapter: "11", title: "Electricity", ...ncert("jesc111") },
      { id: "10-sci-12", subject: "sci", chapter: "12", title: "Magnetic Effects of Electric Current", ...ncert("jesc112") },
      { id: "10-sst-1", subject: "sst", chapter: "1", title: "The Rise of Nationalism in Europe", ...ncert("jess101") },
      { id: "10-sst-2", subject: "sst", chapter: "2", title: "Nationalism in India", ...ncert("jess102") },
      { id: "10-sst-3", subject: "sst", chapter: "3", title: "Resources and Development", ...ncert("jess201") },
      { id: "10-sst-4", subject: "sst", chapter: "4", title: "Agriculture", ...ncert("jess203") },
      { id: "10-sst-5", subject: "sst", chapter: "5", title: "Power Sharing", ...ncert("jess301") },
      { id: "10-sst-6", subject: "sst", chapter: "6", title: "Federalism", ...ncert("jess302") },
      { id: "10-hin-1", subject: "hin", chapter: "1", title: "सूरदास", ...ncert("jhks101") },
      { id: "10-hin-2", subject: "hin", chapter: "2", title: "तुलसीदास", ...ncert("jhks102") },
    ],
    papers: [
      { id: "10-eng-ex", subject: "eng", title: "English First Flight — official reader", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}jeff1=1-11`, downloadUrl: `${NCERT}jeff101.pdf` },
      { id: "10-math-ex", subject: "math", title: "Mathematics — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}jemh1=1-15`, downloadUrl: `${NCERT}jemh101.pdf` },
      { id: "10-sci-ex", subject: "sci", title: "Science — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}jesc1=1-13`, downloadUrl: `${NCERT}jesc101.pdf` },
      { id: "10-sst-ex", subject: "sst", title: "Social Science History — official papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}jess1=1-5`, downloadUrl: `${NCERT}jess101.pdf` },
      { id: "10-hin-ex", subject: "hin", title: "Hindi क्षितिज — official papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}jhks1=1-17`, downloadUrl: `${NCERT}jhks101.pdf` },
      { id: "10-jkbose", subject: "sci", title: "JKBOSE previous / model papers portal", year: "JKBOSE", kind: "Board papers", viewUrl: JKBOSE_PAPERS, downloadUrl: JKBOSE_PAPERS },
    ],
    books: [
      { id: "10-eng-tb", subject: "eng", title: "First Flight", kind: "Textbook", ...ncertBook("jeff1=0-11", "jeff101") },
      { id: "10-eng-sup", subject: "eng", title: "Footprints without Feet", kind: "Supplementary", ...ncertBook("jefp1=0-10", "jefp101") },
      { id: "10-math-tb", subject: "math", title: "Mathematics Class 10", kind: "Textbook", ...ncertBook("jemh1=0-15", "jemh101") },
      { id: "10-sci-tb", subject: "sci", title: "Science Class 10", kind: "Textbook", ...ncertBook("jesc1=0-13", "jesc101") },
      { id: "10-sst-h", subject: "sst", title: "India and the Contemporary World II", kind: "History", ...ncertBook("jess1=0-5", "jess101") },
      { id: "10-sst-g", subject: "sst", title: "Contemporary India II", kind: "Geography", ...ncertBook("jess2=0-7", "jess201") },
      { id: "10-sst-p", subject: "sst", title: "Democratic Politics II", kind: "Political Science", ...ncertBook("jess3=0-8", "jess301") },
      { id: "10-sst-e", subject: "sst", title: "Understanding Economic Development", kind: "Economics", ...ncertBook("jess4=0-5", "jess401") },
      { id: "10-hin-tb", subject: "hin", title: "क्षितिज भाग 2", kind: "Textbook", ...ncertBook("jhks1=0-17", "jhks101") },
    ],
  },

  "11": {
    label: "Class 11th",
    streams: [
      { id: "med", name: "Medical" },
      { id: "nmed", name: "Non-Medical" },
      { id: "arts", name: "Arts" },
      { id: "com", name: "Commerce" },
    ],
    subjects: [
      { id: "eng", name: "English", stream: "all" },
      { id: "phy", name: "Physics", stream: ["med", "nmed"] },
      { id: "chem", name: "Chemistry", stream: ["med", "nmed"] },
      { id: "bio", name: "Biology", stream: ["med"] },
      { id: "math", name: "Mathematics", stream: ["nmed"] },
      { id: "hist", name: "History", stream: ["arts"] },
      { id: "pol", name: "Political Science", stream: ["arts"] },
      { id: "eco", name: "Economics", stream: ["arts", "com"] },
      { id: "acc", name: "Accountancy", stream: ["com"] },
      { id: "bst", name: "Business Studies", stream: ["com"] },
    ],
    notes: [
      { id: "11-eng-1", subject: "eng", chapter: "1", title: "The Portrait of a Lady", ...ncert("kehb101") },
      { id: "11-eng-2", subject: "eng", chapter: "2", title: "We're Not Afraid to Die…", ...ncert("kehb102") },
      { id: "11-phy-1", subject: "phy", chapter: "1", title: "Units and Measurements", ...ncert("keph101") },
      { id: "11-phy-2", subject: "phy", chapter: "2", title: "Motion in a Straight Line", ...ncert("keph102") },
      { id: "11-phy-3", subject: "phy", chapter: "3", title: "Motion in a Plane", ...ncert("keph103") },
      { id: "11-phy-4", subject: "phy", chapter: "4", title: "Laws of Motion", ...ncert("keph104") },
      { id: "11-chem-1", subject: "chem", chapter: "1", title: "Some Basic Concepts of Chemistry", ...ncert("kech101") },
      { id: "11-chem-2", subject: "chem", chapter: "2", title: "Structure of Atom", ...ncert("kech102") },
      { id: "11-chem-3", subject: "chem", chapter: "3", title: "Classification of Elements and Periodicity", ...ncert("kech103") },
      { id: "11-bio-1", subject: "bio", chapter: "1", title: "The Living World", ...ncert("kebo101") },
      { id: "11-bio-2", subject: "bio", chapter: "2", title: "Biological Classification", ...ncert("kebo102") },
      { id: "11-bio-3", subject: "bio", chapter: "3", title: "Plant Kingdom", ...ncert("kebo103") },
      { id: "11-math-1", subject: "math", chapter: "1", title: "Sets", ...ncert("kemh101") },
      { id: "11-math-2", subject: "math", chapter: "2", title: "Relations and Functions", ...ncert("kemh102") },
      { id: "11-math-3", subject: "math", chapter: "3", title: "Trigonometric Functions", ...ncert("kemh103") },
      { id: "11-hist-1", subject: "hist", chapter: "1", title: "From the Beginning of Time", ...ncert("kehs101") },
      { id: "11-hist-2", subject: "hist", chapter: "2", title: "Writing and City Life", ...ncert("kehs102") },
      { id: "11-pol-1", subject: "pol", chapter: "1", title: "Constitution: Why and How?", ...ncert("keps101") },
      { id: "11-pol-2", subject: "pol", chapter: "2", title: "Rights in the Indian Constitution", ...ncert("keps102") },
      { id: "11-eco-1", subject: "eco", chapter: "1", title: "Indian Economy on the Eve of Independence", ...ncert("keec101") },
      { id: "11-acc-1", subject: "acc", chapter: "1", title: "Introduction to Accounting", ...ncert("keac101") },
      { id: "11-acc-2", subject: "acc", chapter: "2", title: "Theory Base of Accounting", ...ncert("keac102") },
      { id: "11-bst-1", subject: "bst", chapter: "1", title: "Nature and Purpose of Business", ...ncert("kebs101") },
      { id: "11-bst-2", subject: "bst", chapter: "2", title: "Forms of Business Organisation", ...ncert("kebs102") },
    ],
    papers: [
      { id: "11-eng-ex", subject: "eng", title: "Hornbill — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}kehb1=1-8`, downloadUrl: `${NCERT}kehb101.pdf` },
      { id: "11-phy-ex", subject: "phy", title: "Physics — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}keph1=1-7`, downloadUrl: `${NCERT}keph101.pdf` },
      { id: "11-chem-ex", subject: "chem", title: "Chemistry — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}kech1=1-6`, downloadUrl: `${NCERT}kech101.pdf` },
      { id: "11-bio-ex", subject: "bio", title: "Biology — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}kebo1=1-22`, downloadUrl: `${NCERT}kebo101.pdf` },
      { id: "11-math-ex", subject: "math", title: "Mathematics — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}kemh1=1-16`, downloadUrl: `${NCERT}kemh101.pdf` },
      { id: "11-hist-ex", subject: "hist", title: "History — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}kehs1=1-11`, downloadUrl: `${NCERT}kehs101.pdf` },
      { id: "11-pol-ex", subject: "pol", title: "Political Science — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}keps1=1-10`, downloadUrl: `${NCERT}keps101.pdf` },
      { id: "11-eco-ex", subject: "eco", title: "Economics — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}keec1=1-8`, downloadUrl: `${NCERT}keec101.pdf` },
      { id: "11-acc-ex", subject: "acc", title: "Accountancy — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}keac1=1-8`, downloadUrl: `${NCERT}keac101.pdf` },
      { id: "11-bst-ex", subject: "bst", title: "Business Studies — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}kebs1=1-10`, downloadUrl: `${NCERT}kebs101.pdf` },
      { id: "11-jkbose", subject: "eng", title: "JKBOSE previous / model papers portal", year: "JKBOSE", kind: "Board papers", viewUrl: JKBOSE_PAPERS, downloadUrl: JKBOSE_PAPERS },
    ],
    books: [
      { id: "11-eng-tb", subject: "eng", title: "Hornbill", kind: "Textbook", ...ncertBook("kehb1=0-8", "kehb101") },
      { id: "11-phy-tb", subject: "phy", title: "Physics Part I", kind: "Textbook", ...ncertBook("keph1=0-7", "keph101") },
      { id: "11-chem-tb", subject: "chem", title: "Chemistry Part I", kind: "Textbook", ...ncertBook("kech1=0-6", "kech101") },
      { id: "11-bio-tb", subject: "bio", title: "Biology Class 11", kind: "Textbook", ...ncertBook("kebo1=0-22", "kebo101") },
      { id: "11-math-tb", subject: "math", title: "Mathematics Class 11", kind: "Textbook", ...ncertBook("kemh1=0-16", "kemh101") },
      { id: "11-hist-tb", subject: "hist", title: "Themes in World History", kind: "Textbook", ...ncertBook("kehs1=0-11", "kehs101") },
      { id: "11-pol-tb", subject: "pol", title: "Indian Constitution at Work", kind: "Textbook", ...ncertBook("keps1=0-10", "keps101") },
      { id: "11-eco-tb", subject: "eco", title: "Indian Economic Development", kind: "Textbook", ...ncertBook("keec1=0-8", "keec101") },
      { id: "11-acc-tb", subject: "acc", title: "Financial Accounting Part I", kind: "Textbook", ...ncertBook("keac1=0-8", "keac101") },
      { id: "11-bst-tb", subject: "bst", title: "Business Studies Class 11", kind: "Textbook", ...ncertBook("kebs1=0-10", "kebs101") },
    ],
  },

  "12": {
    label: "Class 12th",
    streams: [
      { id: "med", name: "Medical" },
      { id: "nmed", name: "Non-Medical" },
      { id: "arts", name: "Arts" },
      { id: "com", name: "Commerce" },
    ],
    subjects: [
      { id: "eng", name: "English", stream: "all" },
      { id: "phy", name: "Physics", stream: ["med", "nmed"] },
      { id: "chem", name: "Chemistry", stream: ["med", "nmed"] },
      { id: "bio", name: "Biology", stream: ["med"] },
      { id: "math", name: "Mathematics", stream: ["nmed"] },
      { id: "hist", name: "History", stream: ["arts"] },
      { id: "pol", name: "Political Science", stream: ["arts"] },
      { id: "eco", name: "Economics", stream: ["arts", "com"] },
      { id: "acc", name: "Accountancy", stream: ["com"] },
      { id: "bst", name: "Business Studies", stream: ["com"] },
    ],
    notes: [
      { id: "12-eng-1", subject: "eng", chapter: "1", title: "The Last Lesson", ...ncert("lefl101") },
      { id: "12-eng-2", subject: "eng", chapter: "2", title: "Lost Spring", ...ncert("lefl102") },
      { id: "12-eng-3", subject: "eng", chapter: "3", title: "Deep Water", ...ncert("lefl103") },
      { id: "12-phy-1", subject: "phy", chapter: "1", title: "Electric Charges and Fields", ...ncert("leph101") },
      { id: "12-phy-2", subject: "phy", chapter: "2", title: "Electrostatic Potential and Capacitance", ...ncert("leph102") },
      { id: "12-phy-3", subject: "phy", chapter: "3", title: "Current Electricity", ...ncert("leph103") },
      { id: "12-chem-1", subject: "chem", chapter: "1", title: "Solutions", ...ncert("lech101") },
      { id: "12-chem-2", subject: "chem", chapter: "2", title: "Electrochemistry", ...ncert("lech102") },
      { id: "12-chem-3", subject: "chem", chapter: "3", title: "Chemical Kinetics", ...ncert("lech103") },
      { id: "12-bio-1", subject: "bio", chapter: "1", title: "Sexual Reproduction in Flowering Plants", ...ncert("lebo101") },
      { id: "12-bio-2", subject: "bio", chapter: "2", title: "Human Reproduction", ...ncert("lebo102") },
      { id: "12-bio-3", subject: "bio", chapter: "3", title: "Human Reproduction continued", ...ncert("lebo103") },
      { id: "12-math-1", subject: "math", chapter: "1", title: "Relations and Functions", ...ncert("lemh101") },
      { id: "12-math-2", subject: "math", chapter: "2", title: "Inverse Trigonometric Functions", ...ncert("lemh102") },
      { id: "12-math-3", subject: "math", chapter: "3", title: "Matrices", ...ncert("lemh103") },
      { id: "12-hist-1", subject: "hist", chapter: "1", title: "Bricks, Beads and Bones", ...ncert("lehs101") },
      { id: "12-hist-2", subject: "hist", chapter: "2", title: "Kings, Farmers and Towns", ...ncert("lehs102") },
      { id: "12-pol-1", subject: "pol", chapter: "1", title: "The End of Bipolarity", ...ncert("leps101") },
      { id: "12-pol-2", subject: "pol", chapter: "2", title: "Contemporary Centres of Power", ...ncert("leps102") },
      { id: "12-eco-1", subject: "eco", chapter: "1", title: "Introduction to Macroeconomics", ...ncert("leec101") },
      { id: "12-eco-2", subject: "eco", chapter: "2", title: "National Income Accounting", ...ncert("leec102") },
      { id: "12-acc-1", subject: "acc", chapter: "1", title: "Accounting for Partnership Firms", ...ncert("leac101") },
      { id: "12-acc-2", subject: "acc", chapter: "2", title: "Accounting for Partnership — reconstitution", ...ncert("leac102") },
      { id: "12-bst-1", subject: "bst", chapter: "1", title: "Nature and Significance of Management", ...ncert("lebs101") },
      { id: "12-bst-2", subject: "bst", chapter: "2", title: "Principles of Management", ...ncert("lebs102") },
    ],
    papers: [
      { id: "12-eng-ex", subject: "eng", title: "Flamingo — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}lefl1=1-8`, downloadUrl: `${NCERT}lefl101.pdf` },
      { id: "12-phy-ex", subject: "phy", title: "Physics — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}leph1=1-8`, downloadUrl: `${NCERT}leph101.pdf` },
      { id: "12-chem-ex", subject: "chem", title: "Chemistry — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}lech1=1-5`, downloadUrl: `${NCERT}lech101.pdf` },
      { id: "12-bio-ex", subject: "bio", title: "Biology — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}lebo1=1-13`, downloadUrl: `${NCERT}lebo101.pdf` },
      { id: "12-math-ex", subject: "math", title: "Mathematics — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}lemh1=1-6`, downloadUrl: `${NCERT}lemh101.pdf` },
      { id: "12-hist-ex", subject: "hist", title: "History — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}lehs1=1-4`, downloadUrl: `${NCERT}lehs101.pdf` },
      { id: "12-pol-ex", subject: "pol", title: "Political Science — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}leps1=1-7`, downloadUrl: `${NCERT}leps101.pdf` },
      { id: "12-eco-ex", subject: "eco", title: "Economics — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}leec1=1-6`, downloadUrl: `${NCERT}leec101.pdf` },
      { id: "12-acc-ex", subject: "acc", title: "Accountancy — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}leac1=1-5`, downloadUrl: `${NCERT}leac101.pdf` },
      { id: "12-bst-ex", subject: "bst", title: "Business Studies — official chapter papers", year: "NCERT", kind: "Chapter papers", viewUrl: `${NCERT_READ}lebs1=1-8`, downloadUrl: `${NCERT}lebs101.pdf` },
      { id: "12-jkbose", subject: "eng", title: "JKBOSE previous / model papers portal", year: "JKBOSE", kind: "Board papers", viewUrl: JKBOSE_PAPERS, downloadUrl: JKBOSE_PAPERS },
    ],
    books: [
      { id: "12-eng-tb", subject: "eng", title: "Flamingo", kind: "Textbook", ...ncertBook("lefl1=0-8", "lefl101") },
      { id: "12-eng-sup", subject: "eng", title: "Vistas", kind: "Supplementary", ...ncertBook("levt1=0-8", "levt101") },
      { id: "12-phy-tb", subject: "phy", title: "Physics Part I", kind: "Textbook", ...ncertBook("leph1=0-8", "leph101") },
      { id: "12-chem-tb", subject: "chem", title: "Chemistry Part I", kind: "Textbook", ...ncertBook("lech1=0-5", "lech101") },
      { id: "12-bio-tb", subject: "bio", title: "Biology Class 12", kind: "Textbook", ...ncertBook("lebo1=0-13", "lebo101") },
      { id: "12-math-tb", subject: "math", title: "Mathematics Part I", kind: "Textbook", ...ncertBook("lemh1=0-6", "lemh101") },
      { id: "12-hist-tb", subject: "hist", title: "Themes in Indian History I", kind: "Textbook", ...ncertBook("lehs1=0-4", "lehs101") },
      { id: "12-pol-tb", subject: "pol", title: "Contemporary World Politics", kind: "Textbook", ...ncertBook("leps1=0-7", "leps101") },
      { id: "12-eco-tb", subject: "eco", title: "Introductory Macroeconomics", kind: "Textbook", ...ncertBook("leec1=0-6", "leec101") },
      { id: "12-acc-tb", subject: "acc", title: "Accountancy Part I", kind: "Textbook", ...ncertBook("leac1=0-5", "leac101") },
      { id: "12-bst-tb", subject: "bst", title: "Business Studies Part I", kind: "Textbook", ...ncertBook("lebs1=0-8", "lebs101") },
    ],
  },
};
